import React, { useRef, useEffect, useState } from 'react';
import type { SpineAnalysisResult, FootAnalysisResult } from '@/types';
import type { Translations, Lang } from '@/lib/i18n';

function esc(s: unknown): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

interface ReportModalProps {
  open: boolean;
  onClose: () => void;
  modality: 'spine' | 'foot';
  spineResult?: SpineAnalysisResult | null;
  footResult?: FootAnalysisResult | null;
  patientAge: string;
  patientGender: string;
  notes: string;
  lang: Lang;
  t: Translations;
}

export const ReportModal: React.FC<ReportModalProps> = ({
  open, onClose, modality, spineResult, footResult, patientAge, patientGender, notes, lang, t
}) => {
  const contentRef    = useRef<HTMLDivElement>(null);
  const [pdfLoading, setPdfLoading] = useState(false);

  // CRITICAL FIX: hooks MUST come before any conditional return.
  // Previously useEffect was after `if (!open) return null` — Rules of Hooks violation.
  useEffect(() => {
    if (!open) return;
    // iOS Safari doesn't honour overflow:hidden on body alone — the scroll
    // position is also locked by fixing the body to its current scroll offset,
    // then restored on close so the viewport doesn't jump to the top.
    const scrollY = window.scrollY;
    const prevOverflow = document.body.style.overflow;
    const prevPosition = document.body.style.position;
    const prevTop      = document.body.style.top;
    const prevWidth    = document.body.style.width;
    document.body.style.overflow = 'hidden';
    document.body.style.position = 'fixed';
    document.body.style.top      = `-${scrollY}px`;
    document.body.style.width    = '100%';
    return () => {
      document.body.style.overflow = prevOverflow;
      document.body.style.position = prevPosition;
      document.body.style.top      = prevTop;
      document.body.style.width    = prevWidth;
      window.scrollTo(0, scrollY);
    };
  }, [open]);

  if (!open) return null;

  const dateLocale = lang === 'tr' ? 'tr-TR' : lang === 'ar' ? 'ar-SA' : 'en-US';
  const date = new Date().toLocaleDateString(dateLocale, { year:'numeric', month:'long', day:'numeric' });
  const time = new Date().toLocaleTimeString(dateLocale);

  // ── Localized report labels ────────────────────────────────────
  const lbl = {
    scoTitle:  lang==='ar'?'تقرير جنف سريري':lang==='en'?'Scoliosis Clinical Report':'Skolyoz Klinik Raporu',
    footTitle: lang==='ar'?'تقرير القدم المسطحة السريري':lang==='en'?'Pes Planus Clinical Report':'Pes Planus Klinik Raporu',
    ptInfo:    lang==='ar'?'بيانات المريض':lang==='en'?'Patient Information':'Hasta Bilgileri',
    age:       t.pAge, gender: t.pGen,
    imgQual:   lang==='ar'?'جودة الصورة':lang==='en'?'Image Quality':'Görüntü Kalitesi',
    conf:      lang==='ar'?'الثقة':lang==='en'?'Confidence':'Güven',
    vertCount: lang==='ar'?'عدد الفقرات':lang==='en'?'Vertebrae Count':'Vertebra Sayısı',
    view:      lang==='ar'?'العرض':lang==='en'?'View':'Görüş',
    meas:      lang==='ar'?'نتائج القياس':lang==='en'?'Measurement Results':'Ölçüm Sonuçları',
    curve:     lang==='ar'?'الانحناء':lang==='en'?'Curve':'Eğrilik',
    cobbAngle: lang==='ar'?'زاوية كوب':lang==='en'?'Cobb Angle':'Cobb Açısı',
    sev:       lang==='ar'?'الشدة':lang==='en'?'Severity':'Şiddet',
    loc:       lang==='ar'?'الموقع':lang==='en'?'Location':'Konum',
    upperV:    lang==='ar'?'الفقرة العلوية':lang==='en'?'Upper Vertebra':'Üst Vertebra',
    lowerV:    lang==='ar'?'الفقرة السفلية':lang==='en'?'Lower Vertebra':'Alt Vertebra',
    apex:      lang==='ar'?'الأوج':lang==='en'?'Apex':'Apeks',
    clinEval:  t.recTitle,
    ageRec:    t.rt1,
    treatPlan: t.rt2,
    followUp:  t.rt3,
    imaging:   t.imgTitle,
    docNotes:  t.notes,
    ortho:     t.orthoTitle,
    foot:      lang==='ar'?'القدم':lang==='en'?'Foot':'Ayak',
    dir:       lang==='ar'?'الاتجاه':lang==='en'?'Direction':'Yön',
    flex:      lang==='ar'?'المرونة':lang==='en'?'Flexibility':'Esneklik',
    disc:      lang==='ar'
      ? '⚕ تم إنشاء هذا التقرير بتحليل الذكاء الاصطناعي CobbAI. لا يحل محل التشخيص الطبي. للتشخيص والعلاج النهائي، راجع أخصائي الطب الطبيعي المرخص.'
      : lang==='en'
      ? '⚕ This report was generated by CobbAI AI analysis. Not a substitute for medical diagnosis. Consult a licensed PMR specialist for definitive diagnosis and treatment.'
      : '⚕ Bu rapor CobbAI yapay zeka analizi ile oluşturulmuştur. Tıbbi tanı yerine geçmez. Kesin tanı ve tedavi için lisanslı FTR Uzman Hekimine başvurunuz.',
  };

  // ── Localized value lookups (raw AI enum strings must never be rendered as-is) ──
  const imgQualLbl: Record<string, string> = {
    good:         lang==='ar'?'جيدة':lang==='en'?'Good':'İyi',
    poor:         lang==='ar'?'ضعيفة':lang==='en'?'Poor':'Zayıf',
    unacceptable: lang==='ar'?'غير مقبولة':lang==='en'?'Unacceptable':'Kabul Edilemez',
  };
  const viewLbl: Record<string, string> = {
    PA:      'PA',
    AP:      'AP',
    unknown: lang==='ar'?'غير معروف':lang==='en'?'Unknown':'Bilinmiyor',
  };
  const footSideLbl: Record<string, string> = {
    left:    lang==='ar'?'يسار':lang==='en'?'Left':'Sol',
    right:   lang==='ar'?'يمين':lang==='en'?'Right':'Sağ',
    unknown: lang==='ar'?'غير معروف':lang==='en'?'Unknown':'Bilinmiyor',
  };

  // ── Browser print (quick path) ────────────────────────────────
  const handlePrint = () => {
    const content = contentRef.current?.innerHTML ?? '';
    const win = window.open('', '_blank', 'width=800,height=900');
    if (!win) return;
    const dir = lang === 'ar' ? 'rtl' : 'ltr';
    win.document.write(`<!DOCTYPE html><html dir="${dir}" lang="${lang}"><head><title>CobbAI Report</title><style>
      body{margin:24px;font-family:Georgia,serif;color:#111;font-size:13px;line-height:1.6;direction:${dir}}
      h1{font-size:20px;margin-bottom:4px} h2{font-size:15px;margin:16px 0 6px;border-bottom:1px solid #ccc;padding-bottom:4px}
      table{width:100%;border-collapse:collapse;margin:8px 0;font-size:12px}
      th{background:#f0f0f0;padding:6px 10px;text-align:start;font-weight:700}
      td{padding:6px 10px;border-bottom:1px solid #eee}
      .pill{display:inline-block;padding:2px 8px;border-radius:12px;font-size:11px;font-weight:700}
      .disclaimer{font-size:11px;color:#666;border-top:1px solid #ccc;margin-top:16px;padding-top:8px}
      @media print{body{margin:12px}}
    </style></head><body>${content}</body></html>`);
    win.document.close();
    setTimeout(() => win.print(), 500);
  };

  // ── PDF download: html2canvas → jsPDF ────────────────────────
  // Fixes vs old approach:
  //   1. scale = devicePixelRatio * 2  →  crisp text on Retina screens
  //   2. height = el.scrollHeight      →  captures full content, not just viewport
  //   3. Multi-page: splits canvas into A4 slices automatically
  const handleDownloadPDF = async () => {
    const el = contentRef.current;
    if (!el || pdfLoading) return;
    setPdfLoading(true);
    try {
      // Dynamic imports — avoid adding ~400 KB to the initial bundle
      const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
        import('html2canvas'),
        import('jspdf'),
      ]);

      const dpr    = window.devicePixelRatio || 1;
      const scale  = Math.min(2, Math.max(1, dpr));  // cap at 2× — 4× causes OOM on iPad

      const canvas = await html2canvas(el, {
        scale,
        useCORS:       true,
        logging:       false,
        scrollX:       0,
        scrollY:       0,
        width:         el.scrollWidth,
        height:        el.scrollHeight,   // ← full height (not just what's in viewport)
        windowWidth:   el.scrollWidth,
        windowHeight:  el.scrollHeight,
        backgroundColor: '#0e1419',       // match modal background
      });

      // A4 dimensions in mm
      const A4_W = 210, A4_H = 297;
      const pdf  = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

      // Map canvas px → mm on A4 width
      const imgW   = A4_W;
      const imgH   = (canvas.height / canvas.width) * A4_W;
      const pageH  = A4_H;

      if (imgH <= pageH) {
        // Single page — fits without splitting
        pdf.addImage(canvas.toDataURL('image/jpeg', 0.92), 'JPEG', 0, 0, imgW, imgH);
      } else {
        // Multi-page: slice the canvas into A4-height strips.
        // BUG FIX: previous code used drawImage(canvas, 0, -srcY) which shifts the
        // whole canvas up without clipping — every page drew the same full image.
        // Correct: use the 9-argument drawImage(src, sx,sy,sw,sh, dx,dy,dw,dh) form
        // to clip exactly one page-height strip from the source canvas.
        const pxPerPage = Math.floor((pageH / imgH) * canvas.height);
        let srcY = 0;

        while (srcY < canvas.height) {
          const srcH = Math.min(pxPerPage, canvas.height - srcY);

          const slice = document.createElement('canvas');
          slice.width  = canvas.width;
          slice.height = srcH;
          // Clip exactly [srcY, srcY+srcH] rows from the source canvas
          slice.getContext('2d')!.drawImage(
            canvas,
            0, srcY, canvas.width, srcH,   // source rectangle
            0, 0,    slice.width,  srcH    // destination rectangle
          );

          const sliceH = (srcH / canvas.height) * imgH;
          if (srcY > 0) pdf.addPage();
          pdf.addImage(slice.toDataURL('image/jpeg', 0.92), 'JPEG', 0, 0, imgW, sliceH);

          srcY += srcH;
        }
      }

      const reportWord = lang==='ar'?'تقرير':lang==='en'?'Report':'Rapor';
      pdf.save(`CobbAI-${reportWord}-${new Date().toISOString().slice(0, 10)}.pdf`);
    } catch (err) {
      console.error('[CobbAI] PDF export failed:', err);
      // Fall back to browser print
      handlePrint();
    } finally {
      setPdfLoading(false);
    }
  };

  const buildSpineReport = () => {
    if (!spineResult) return '';
    const curves = spineResult.curves ?? [];
    return `
      <h1>📋 CobbAI — ${lbl.scoTitle}</h1>
      <p style="color:#555;font-size:12px">${date} · ${time} · cobbai.vercel.app</p>
      <h2>${lbl.ptInfo}</h2>
      <table>
        <tr><th>${lbl.age}</th><td>${esc(patientAge)||'—'}</td><th>${lbl.gender}</th><td>${esc(patientGender)||'—'}</td></tr>
        <tr><th>${lbl.imgQual}</th><td>${esc(imgQualLbl[spineResult.image_quality] ?? spineResult.image_quality)}</td><th>${lbl.conf}</th><td>${esc(t.conf[spineResult.measurement_confidence] ?? spineResult.measurement_confidence)}</td></tr>
        <tr><th>${lbl.vertCount}</th><td>${esc(spineResult.vertebrae_detected)}</td><th>${lbl.view}</th><td>${esc(viewLbl[spineResult.view_type] ?? spineResult.view_type)}</td></tr>
      </table>
      <h2>${lbl.meas}</h2>
      <table>
        <tr><th>#</th><th>${lbl.curve}</th><th>${lbl.cobbAngle}</th><th>${lbl.sev}</th><th>${lbl.loc}</th><th>${lbl.upperV}</th><th>${lbl.lowerV}</th><th>${lbl.apex}</th></tr>
        ${curves.map((c,i) => `
          <tr>
            <td>${i+1}</td>
            <td>${esc(c.label)}</td>
            <td><strong>${esc(c.cobb_angle)}°</strong></td>
            <td><span class="pill" style="background:${sevBg(c.severity)};color:${sevCol(c.severity)}">${esc(t.sevS[c.severity] ?? c.severity)}</span></td>
            <td>${esc(c.curve_location)}</td>
            <td>${esc(c.upper_vertebra_name)||'—'}</td>
            <td>${esc(c.lower_vertebra_name)||'—'}</td>
            <td>${esc(c.apical_vertebra_name)||'—'}</td>
          </tr>`).join('')}
      </table>
      <h2>${lbl.clinEval}</h2>
      <p>${esc(spineResult.overall_description)||'—'}</p>
      <h2>${lbl.ageRec}</h2>
      <p>${esc(spineResult.age_based_recommendation||'—').replace(/\n/g,'<br>')}</p>
      <h2>${lbl.treatPlan}</h2>
      <p>${esc(spineResult.treatment_plan||'—').replace(/\n/g,'<br>')}</p>
      <h2>${lbl.followUp}</h2>
      <p>${esc(spineResult.followup_plan)||'—'}</p>
      ${spineResult.imaging_indications && spineResult.imaging_indications!=='None' ? `<h2>${lbl.imaging}</h2><p>${esc(spineResult.imaging_indications)}</p>` : ''}
      ${notes ? `<h2>${lbl.docNotes}</h2><p>${esc(notes).replace(/\n/g,'<br>')}</p>` : ''}
      <div class="disclaimer">${lbl.disc}</div>
    `;
  };

  const buildFootReport = () => {
    if (!footResult) return '';
    return `
      <h1>📋 CobbAI — ${lbl.footTitle}</h1>
      <p style="color:#555;font-size:12px">${date} · ${time} · cobbai.vercel.app</p>
      <h2>${lbl.ptInfo}</h2>
      <table>
        <tr><th>${lbl.age}</th><td>${esc(patientAge)||'—'}</td><th>${lbl.gender}</th><td>${esc(patientGender)||'—'}</td></tr>
        <tr><th>${lbl.foot}</th><td>${esc(footSideLbl[footResult.foot_side] ?? footResult.foot_side)}</td><th>${lbl.conf}</th><td>${esc(t.conf[footResult.measurement_confidence] ?? footResult.measurement_confidence)}</td></tr>
      </table>
      <h2>${lbl.meas}</h2>
      <table>
        <tr><th>${t.flM}</th><td><strong>${footResult.meary_angle != null ? esc(footResult.meary_angle) + '°' : '—'}</strong></td><th>${lbl.dir}</th><td>${esc(t.mearyDir[footResult.meary_direction] ?? footResult.meary_direction)}</td></tr>
        <tr><th>${t.flC}</th><td>${footResult.calcaneal_pitch != null ? esc(footResult.calcaneal_pitch) + '°' : '—'}</td><th>${t.flT}</th><td>${footResult.talar_declination != null ? esc(footResult.talar_declination) + '°' : '—'}</td></tr>
        <tr><th>${lbl.sev}</th><td>${esc(t.sevF[footResult.severity] ?? footResult.severity)}</td><th>${lbl.flex}</th><td>${esc(t.flex[footResult.flexibility] ?? footResult.flexibility)}</td></tr>
      </table>
      <h2>${lbl.clinEval}</h2>
      <p>${esc(footResult.overall_description)||'—'}</p>
      <h2>${lbl.treatPlan}</h2>
      <p>${esc(footResult.treatment_plan||'—').replace(/\n/g,'<br>')}</p>
      ${footResult.orthotic_recommendations ? `<h2>${lbl.ortho}</h2><p>${esc(footResult.orthotic_recommendations)}</p>` : ''}
      ${notes ? `<h2>${lbl.docNotes}</h2><p>${esc(notes).replace(/\n/g,'<br>')}</p>` : ''}
      <div class="disclaimer">${lbl.disc}</div>
    `;
  };

  const html = modality === 'spine' ? buildSpineReport() : buildFootReport();

  return (
    <div style={{ position:'fixed', inset:0, zIndex:10000, background:'rgba(0,0,0,.88)', display:'flex', alignItems:'flex-start', justifyContent:'center', padding:'1rem', overflowY:'auto' }}
      onClick={e => { if (e.target === e.currentTarget) onClose(); }}>
      <div style={{ background:'#0e1419', border:'1px solid rgba(255,255,255,.15)', borderRadius:14, maxWidth:700, width:'100%', margin:'2rem auto' }}>
        <div style={{ padding:'16px 20px', borderBottom:'1px solid rgba(255,255,255,.08)', display:'flex', alignItems:'center', justifyContent:'space-between' }}>
          <span style={{ fontSize:18, fontWeight:600 }}>{t.reportTitle}</span>
          <div style={{ display:'flex', gap:8 }}>
            {/* PDF download — html2canvas full-page, crisp */}
            <button
              onClick={handleDownloadPDF}
              disabled={pdfLoading}
              style={{ padding:'7px 14px', background: pdfLoading ? '#065a2a' : '#00c853', color:'#000', border:'none', borderRadius:7, fontSize:13, fontWeight:700, cursor: pdfLoading ? 'wait' : 'pointer', minWidth:110, display:'flex', alignItems:'center', gap:6 }}>
              {pdfLoading
                ? <><span style={{ width:12, height:12, border:'2px solid rgba(0,0,0,.3)', borderTopColor:'#000', borderRadius:'50%', animation:'_spin .7s linear infinite', flexShrink:0 }}/>İndiriliyor…</>
                : '⬇ PDF İndir'}
            </button>
            {/* Browser print */}
            <button onClick={handlePrint} style={{ padding:'7px 14px', background:'transparent', color:'#7a8fa0', border:'1px solid rgba(255,255,255,.15)', borderRadius:7, fontSize:13, fontWeight:600, cursor:'pointer' }}>
              🖨 {t.printBtn}
            </button>
            <button onClick={onClose} style={{ width:32, height:32, border:'1px solid rgba(255,255,255,.15)', borderRadius:6, background:'transparent', color:'#7a8fa0', fontSize:18, cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center' }}>✕</button>
          </div>
        </div>
        <div ref={contentRef} style={{ padding:24, fontSize:14, color:'#b0bec5', lineHeight:1.7 }}
          dangerouslySetInnerHTML={{ __html: html }} />
      </div>
    </div>
  );
};

function sevBg(s: string) { return {normal:'rgba(0,214,143,.15)',mild:'rgba(240,160,69,.15)',moderate:'rgba(240,120,50,.15)',severe:'rgba(224,85,85,.15)'}[s]??'rgba(120,130,140,.15)'; }
function sevCol(s: string) { return {normal:'#00d68f',mild:'#f0a045',moderate:'#f07832',severe:'#e05555'}[s]??'#7a8fa0'; }

export default ReportModal;
